=== iclodoaldo/trabalhoXml2/src/XSD_ex_2.xsd
<?xml version="1.0"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<xs:schema 
    version="1.0"
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    elementFormDefault="qualified">
    
    <xs:element name="cidade">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="nome" type="xs:string"/>
                <xs:element name="uf" type="xs:string"/>
                <xs:element name="atualizacao" type="xs:string"/>
                <xs:element name="dia" type="tipoDia" minOccurs="6" maxOccurs="6"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <xs:complexType name="tipoDia">
        <xs:sequence>
            <xs:element name="manha" type="tipoManha" />
            <xs:element name="tarde" type="tipoTarde" />
            <xs:element name="noite" type="tipoNoite" />
            <xs:element name="media" type="xs:decimal"/>
        </xs:sequence>
        <xs:attribute name="data" type="xs:date"/>
    </xs:complexType>
    
    <xs:complexType name="tipoManha">
        <xs:sequence>
            <xs:element name="altura" type="xs:decimal"/>
        </xs:sequence>
    </xs:complexType>
            
    <xs:complexType name="tipoTarde">
        <xs:sequence>
            <xs:element name="altura" type="xs:decimal"/>
        </xs:sequence>
    </xs:complexType>           
    
    <xs:complexType name="tipoNoite">
        <xs:sequence>
            <xs:element name="agitacao" type="xs:string"/>
            <xs:element name="altura" type="xs:decimal"/>           
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== iclodoaldo/trabalhoXml2/src/SaidaExercicio2.xml
<?xml version="1.0" encoding="utf-8"?>
<cidade xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://github.com/iclodoaldo/trabalhoXml2/blob/master/src/XSD_ex_2.xsd"><nome>Arraial do Cabo</nome><uf>RJ</uf><atualizacao>2015-09-09</atualizacao><dia data="2015-09-10"><manha><altura>1.6</altura></manha><tarde><altura>1.4</altura></tarde><noite><agitacao>Fraco</agitacao><altura>1.3</altura></noite><media>23.0</media></dia><dia data="2015-09-11"><manha><altura>1.0</altura></manha><tarde><altura>1.0</altura></tarde><noite><agitacao>Fraco</agitacao><altura>1.1</altura></noite><media>26.0</media></dia><dia data="2015-09-12"><manha><altura>1.8</altura></manha><tarde><altura>1.5</altura></tarde><noite><agitacao>Fraco</agitacao><altura>1.4</altura></noite><media>23.0</media></dia><dia data="2015-09-13"><manha><altura>1.6</altura></manha><tarde><altura>1.4</altura></tarde><noite><agitacao>Fraco</agitacao><altura>1.3</altura></noite><media>22.5</media></dia><dia data="2015-09-14"><manha><altura>1.6</altura></manha><tarde><altura>1.4</altura></tarde><noite><agitacao>Fraco</agitacao><altura>1.3</altura></noite><media>22.5</media></dia><dia data="2015-09-15"><manha><altura>1.6</altura></manha><tarde><altura>1.4</altura></tarde><noite><agitacao>Fraco</agitacao><altura>1.3</altura></noite><media>24.0</media></dia></cidade>
